/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file,10 choose Tools | Templates
 * and open the template in the editor.
 */
package marineExperience.view;

import marineExperience.dao.DataSource;
import marineExperience.dao.Dao;
import marineExperience.model.Usuario;
import javax.swing.JOptionPane;
/**
 *
 * @author jonat
 */
public class LoginView extends javax.swing.JFrame {
    /**
     * Creates new form loginView
     */
    public LoginView() {
        super("Marine Experience - Login");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jBCancelar = new javax.swing.JButton();
        jLCadastro = new javax.swing.JLabel();
        jPFSenha = new javax.swing.JPasswordField();
        jTFNome = new javax.swing.JTextField();
        jBEntrar = new javax.swing.JButton();
        jLSenha = new javax.swing.JLabel();
        jLNome = new javax.swing.JLabel();
        jLMarine = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 413, 321));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 413, 321));
        setMinimumSize(new java.awt.Dimension(413, 321));
        setSize(new java.awt.Dimension(413, 321));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jBCancelar.setBackground(new java.awt.Color(51, 102, 255));
        jBCancelar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jBCancelar);
        jBCancelar.setBounds(220, 210, 140, 21);

        jLCadastro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLCadastro.setForeground(new java.awt.Color(51, 0, 204));
        jLCadastro.setText("cadastrar-se");
        jLCadastro.setAutoscrolls(true);
        jLCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCadastroMouseClicked(evt);
            }
        });
        getContentPane().add(jLCadastro);
        jLCadastro.setBounds(280, 140, 80, 15);

        jPFSenha.setText("admin");
        getContentPane().add(jPFSenha);
        jPFSenha.setBounds(110, 110, 250, 20);

        jTFNome.setText("admin");
        getContentPane().add(jTFNome);
        jTFNome.setBounds(110, 80, 250, 20);

        jBEntrar.setBackground(new java.awt.Color(51, 102, 255));
        jBEntrar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBEntrar.setForeground(new java.awt.Color(255, 255, 255));
        jBEntrar.setText("Entrar");
        jBEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(jBEntrar);
        jBEntrar.setBounds(50, 210, 140, 21);

        jLSenha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLSenha.setForeground(new java.awt.Color(51, 102, 255));
        jLSenha.setText("Senha");
        getContentPane().add(jLSenha);
        jLSenha.setBounds(50, 110, 53, 15);

        jLNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLNome.setForeground(new java.awt.Color(51, 102, 255));
        jLNome.setText("Nome");
        getContentPane().add(jLNome);
        jLNome.setBounds(50, 80, 53, 15);

        jLMarine.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLMarine.setForeground(new java.awt.Color(0, 0, 255));
        jLMarine.setText("Marine Experience");
        getContentPane().add(jLMarine);
        jLMarine.setBounds(20, 20, 150, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication31/assets/timao.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 413, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCadastroMouseClicked
        abreCadastro();
    }//GEN-LAST:event_jLCadastroMouseClicked

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        limpacampos();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEntrarActionPerformed
        autenticacao();
    }//GEN-LAST:event_jBEntrarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void abreCadastro() {
        AddUserView au = new AddUserView();
        au.setVisible(true);
    }

    private void autenticacao(){
        DataSource dataSource = new DataSource();
        Dao dao = new Dao(dataSource);
        Usuario usuario = dao.findUser(jTFNome.getText(), jPFSenha.getText());
        if (usuario != null) {
            this.dispose();
            MapPrincipalView t = new MapPrincipalView();
            t.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Nome ou Senha está inválido!");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBEntrar;
    private javax.swing.JLabel jLCadastro;
    private javax.swing.JLabel jLMarine;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPFSenha;
    private javax.swing.JTextField jTFNome;
    // End of variables declaration//GEN-END:variables

    private void limpacampos() {
        jTFNome.setText("");
        jPFSenha.setText("");
    }
}
